### ISSUE TITLE
Transaction fee amount

### ISSUE THREAD

**Issue by KernelPryanic** [PatrickAlphaC/nft-mix#18]
Hello! I have a question regarding the transaction fee amount. Does it reflect real fee amount which I can expect on the Mainnet?

**Comment by PatrickAlphaC** [comment]
Great question. Are you talking about the Chainlink fees or the gas fees? 

For Chainlink VRF, you can find all the fees for each network here: https://docs.chain.link/docs/vrf-contracts/

I'm closing this issue for now, but feel free to follow up
