### ISSUE TITLE
Error when trying to deploy the simple NFT.

### ISSUE THREAD

**Issue by Edark94** [PatrickAlphaC/nft-mix#2]
Hello,

I've been trying to do the most basic of things, download the git repo and deploy the simple NFT according to the tutorial. I get the following error message:

Brownie v1.13.3 - Python development framework for Ethereum

NftMixProject is the active project.

Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...

Running 'scripts/simple_collectible/deploy_simple.py::main'...
mnemonic: 'steak unhappy joke dune invite relax candy update agent vacuum bone ignore'
development
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 96, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "", line 4, in main
  File "brownie/network/contract.py", line 158, in __getitem__
    return self._contracts[i]
IndexError: list index out of range
Terminating local RPC client...

I got the same issue trying to run with sudo, nothing works.

**Comment by PatrickAlphaC** [comment]
sorry. Try again.
