### ISSUE TITLE
No contract in SimpleCollectible ContractContainer :(

### ISSUE THREAD

**Issue by iw1000** [PatrickAlphaC/nft-mix#20]
Followed the exact steps in README but I get the following. Does anyone know what I'm doing wrong?

```
lucascheon@Lucass-MacBook-Pro nft % brownie run scripts/simple_collectible/create_collectible.py
Brownie v1.14.6 - Python development framework for Ethereum

NftProject is the active project.

Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...

Running 'scripts/simple_collectible/create_collectible.py::main'...
development
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/simple_collectible/create_collectible.py", line 11, in main
    simple_collectible = SimpleCollectible[len(SimpleCollectible) - 1]
  File "brownie/network/contract.py", line 158, in __getitem__
    return self._contracts[i]
IndexError: list index out of range
Terminating local RPC client...
```

**Comment by PatrickAlphaC** [comment]
Thanks for making this! You're not using a `--network rinkeby` on your command.

When you don't use a network flag, it will default to a local network. This will deploy an NFT based on a contract that has already been deployed. On a local ganache that brownie spins up, no contract has been deployed yet. 

You'll have to run the script in order on a persistent blockchain. The built-in brownie network doesn't persist the blockchain. 

Closing for now, but feel free to follow up.

**Comment by iw1000** [comment]
Hey Patrick. Thanks for the quick response. I'm new to blockchain in general so my questions might be very n00b-ish.

I ran the simple deploy script first and then ran the create script next. Is this what you meant by "running script in order"?

In general, could you elaborate more on what I should be doing to deploy a contract on my local ganache?

**Comment by PatrickAlphaC** [comment]
If you want to deploy to your local ganache, you'll have to run the scripts in order as you mentioned, and add a persistent ganache chain to your list of networks.

```
brownie networks add Ethereum ganache host=http://localhost:8545 chainid=1337
```
Then run the 2 scripts with a `--network ganache` flag
