### ISSUE TITLE
Issue with: brownie run scripts/simple_collectible/create_collectible.py --network rinkeby

### ISSUE THREAD

**Issue by nathanbowley98** [PatrickAlphaC/nft-mix#22]
```
nathan@nathan-VirtualBox:~/Documents/coding/nft/PatrickAlphaC/nftAttempt2/nft$ brownie run scripts/simple_collectible/create_collectible.py --network rinkeby
Brownie v1.14.6 - Python development framework for Ethereum

NftProject is the active project.
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 53, in run
    module = _import_from_path(script)
  File "brownie/project/scripts.py", line 149, in _import_from_path
    _import_cache[import_str] = importlib.import_module(import_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "./scripts/simple_collectible/create_collectible.py", line 3, in <module>
    from scripts.helpful_scripts import OPENSEA_FORMAT
ImportError: cannot import name 'OPENSEA_FORMAT' from 'scripts.helpful_scripts' (/home/nathan/Documents/coding/nft/PatrickAlphaC/nftAttempt2/nft/scripts/helpful_scripts.py)

```
I was looking at the code and the import error doesn't really make sense to me as in scripts.helpful_scripts there is not OPENSEA_FORMAT as that was replaced with OPENSEA_URL in the most recent push so create_collectable.py (within simple collectable) needs to be refactored to line 3 --> from scripts.helpful_scripts import OPENSEA_URL
also on line 16 same file

**Comment by PatrickAlphaC** [comment]
Whoops! You're right! Sorry, fat fingered it. I just pushed an update. Can you try now?

**Comment by nathanbowley98** [comment]
> Whoops! You're right! Sorry, fat fingered it. I just pushed an update. Can you try now?
i didn't pull but when i edited the two things on my own end it worked, only question: will it always cost gas to send the nft's to opensea? theres no way to just send them to opensea programmatically using the lazy minting feature like on the main site page?

**Comment by PatrickAlphaC** [comment]
We aren't sending the NFTs to opensea. We send them to the blockchain, and opensea reads off the blockchain. Whenever we make a state change on a blockchain yes, we have to spend gas. I'm closing this issue for now, but feel free to follow up.

**Comment by PatrickAlphaC** [comment]
You'd have to check the opensea API to use lazy minting
