### ISSUE TITLE
Video tokens will not load on Rarible.

### ISSUE THREAD

**Issue by Bracciata** [PatrickAlphaC/nft-mix#25]
I have uploaded tokens to the Rinkeby Blockchain and they work on Openseas but the video will not load on Rinkeby.rarible.com.

https://rinkeby.rarible.com/token/0x7a3ba87e3b49dd82f0774b8ead207db3e39c9134:30?tab=details
https://testnets.opensea.io/assets/0x7a3ba87e3b49dd82f0774b8ead207db3e39c9134/30

**Comment by PatrickAlphaC** [comment]
Awesome! This is likely an issue with Rarible as opposed to something wrong with your code.

Closing for now, feel free to follow up.

**Comment by moonsh** [comment]
@Bracciata  Were you able to see the video clip right after you minted? or Did you wait for long time to see the video clip through opensea?

**Comment by PatrickAlphaC** [comment]
I had to wait up to 1 hour sometimes :/

Be sure to hit the refresh button!
