### ISSUE TITLE
ValueError: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

### ISSUE THREAD

**Issue by fardums** [PatrickAlphaC/nft-mix#26]
Hi,

I tried to run 'scripts/advanced_collectible/create_collectible.py' 
but got this error. Kindly help:

> Running 'scripts/advanced_collectible/create_collectible.py::main'...
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/advanced_collectible/create_collectible.py", line 11, in main
    transaction = advanced_collectible.createCollectible(
  File "brownie/network/contract.py", line 1692, in __call__
    return self.transact(*args)
  File "brownie/network/contract.py", line 1565, in transact
    return tx["from"].transfer(
  File "brownie/network/account.py", line 642, in transfer
    receipt, exc = self._make_transaction(
  File "brownie/network/account.py", line 725, in _make_transaction
    raise VirtualMachineError(e) from None
  File "brownie/exceptions.py", line 121, in __init__
    raise ValueError(str(exc)) from None
ValueError: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

My question where should I set the gas limit properly?

create_collectible.py

`from brownie import AdvancedCollectible, accounts, config
from scripts.helpful_scripts import get_oubreed
import time

STATIC_SEED = 123

def main():
    dev = accounts.add(config['wallets']['from_key'])
    advanced_collectible = AdvancedCollectible[len(AdvancedCollectible) - 1]
    transaction = advanced_collectible.createCollectible(
        STATIC_SEED, "None", {"from": dev})
    transaction.wait(1)
    requestId = transaction.events['requestedCollectible']['requesId']
    token_id = advance_collectible.requestIdToTokenId(requestId)
    time.sleep(45)
    oubreed = get_oubreed(advanced_collectible.tokenIdToBreed(token_Id))
    print('breed of tokenId {} is {}'.format(token_id, oubreed))`

oubreed is correct as I modified as it is. 

brownie-config.yaml
`dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}

networks:
  default: development
  rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    link_token: "0x01be23585060835e02b77ef475b0cc51aa1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000`

thanks

**Comment by PatrickAlphaC** [comment]
Thanks for this issue, it's likely that you don't have enough ETH or LINK to run the commands. What network are you on?

**Comment by fardums** [comment]
Hi Patrick, thanks for responding, im using rinkeby network and I have enough fund on my ETH and link (7 ETH and 96 LINK). 
this is my cmd`brownie run scripts/advanced_collectible/create_collectible.py --network rinkeby` 
is there anywhere I should set the gas limit then?

**Comment by PatrickAlphaC** [comment]
Yes, you can set it when you make the contract call, but the real resolution should be in running your scripts in order, you shouldn't have to set the limit.

Did you run the following scripts in this order? 

1. `brownie run scripts/advanced_collectible/deploy_advanced.py --network rinkeby`
2. `brownie run scripts/advanced_collectible/fund_collectible.py --network rinkeby`
3. `brownie run scripts/advanced_collectible/create_collectible.py --network rinkeby`

?

**Comment by fardums** [comment]
Thank you so much Patrick! Now it works after I re-run again all those following scripts in order!
