### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rajuu89** [PatrickAlphaC/nft-mix#3]
Hi,
When i run this command i get the following issues Any reason?
"brownie run scripts/simple_collectible/create_collectible.py"

but I have executed following command successfully and deployed without error
"brownie run scripts/simple_collectible/deploy_simple.py"
 

Error

 File "brownie/_cli/run.py", line 50, in main
    args["<filename>"], method_name=args["<function>"] or "main", _include_frame=True
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/simple_collectible/create_collectible.py", line 9, in main
    simple_collectible = SimpleCollectible[len(SimpleCollectible) - 1]
  File "brownie/network/contract.py", line 158, in __getitem__
    return self._contracts[i]
IndexError: list index out of range

**Comment by PatrickAlphaC** [comment]
I just repushed, could you try again?

**Comment by PatrickAlphaC** [comment]
Going to close for now, feel free to @ me here again if this is still an issue.

**Comment by rajuu89** [comment]
Same issue is coming. Do we want to do any external configuration for run simple ERC721 on local computer?

**Comment by SheenyMeg** [comment]
> Hi,
> When i run this command i get the following issues Any reason?
> "brownie run scripts/simple_collectible/create_collectible.py"
> 
> but I have executed following command successfully and deployed without error
> "brownie run scripts/simple_collectible/deploy_simple.py"
> 
> Error
> 
> File "brownie/_cli/run.py", line 50, in main
> args[""], method_name=args[""] or "main", _include_frame=True
> File "brownie/project/scripts.py", line 103, in run
> return_value = f_locals[method_name](*args, **kwargs)
> File "./scripts/simple_collectible/create_collectible.py", line 9, in main
> simple_collectible = SimpleCollectible[len(SimpleCollectible) - 1]
> File "brownie/network/contract.py", line 158, in **getitem**
> return self._contracts[i]
> IndexError: list index out of range

I also met same problem with you. Did you solve it later?

**Comment by PatrickAlphaC** [comment]
Could you re clone the repo and try again?

**Comment by SheenyMeg** [comment]
> Could you re clone the repo and try again?

I did,but still got an error that **IndexError: list index out of range**

**Comment by PatrickAlphaC** [comment]
Does your `deploy_simple.py`  `main` function look like this?

```
def main():
    dev = accounts.add(config["wallets"]["from_key"])
    print(network.show_active())
    publish_source = True if os.getenv("ETHERSCAN_TOKEN") else False
    SimpleCollectible.deploy({"from": dev}, publish_source=publish_source)
```
