### ISSUE TITLE
Issue with importing chainlink and openzeppelin

### ISSUE THREAD

**Issue by keyvleon** [PatrickAlphaC/nft-mix#30]
solc throws an error when brownie compiling.

import function per AdvancedCollectible.sol: (I use the .sol code and .yaml copies from github to rule out typos, but still the same)
```
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";
```

According to the [docs](https://eth-brownie.readthedocs.io/en/stable/compile.html) brownie should have ensured that all remapped paths are allowed. so there's no need to declare "allow_paths"
```
INFO: Could not find files for the given pattern(s).
Brownie v1.16.2 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.6.6
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/AdvancedCollectibles.sol:3:1: ParserError: Source "OpenZeppelin/openzeppelin-contracts@3.4.0/contracts/token/ERC721/ERC721.sol" not found: File outside of allowed directories.
import "OpenZeppelin/openzeppelin-contracts@3.4.0/contracts/token/ERC721/ERC721.sol";
^-----------------------------------------------------------------------------------^

contracts/AdvancedCollectibles.sol:4:1: ParserError: Source "smartcontractkit/chainlink-brownie-contracts@1.0.2/contracts/src/v0.6/VRFConsumerBase.sol" not found: File outside of allowed directories. 
import "smartcontractkit/chainlink-brownie-contracts@1.0.2/contracts/src/v0.6/VRFConsumerBase.sol";
^-------------------------------------------------------------------------------------------------^
```
I then tried to use the actual path instead of remaps as suggested from another user on [stackexchange ](https://ethereum.stackexchange.com/questions/98289/issue-with-importing-chainlink-openzeppelin) but no luck either.......any ideas?
```
import "OpenZeppelin/openzeppelin-contracts@3.4.0/contracts/token/ERC721/ERC721.sol";
import "smartcontractkit/chainlink-brownie-contracts@1.0.2/contracts/src/v0.6/VRFConsumerBase.sol";
```

**Comment by PatrickAlphaC** [comment]
What do your dependencies look like in your `brownie-config.yaml`?

**Comment by fruitybits** [comment]
I ran into this issue because chainlink-brownie-contracts is downgraded. So, you can't copy pasta the .yaml as is. You need to use -> smartcontractkit/chainlink-brownie-contracts@0.2.1.

**Comment by keyvleon** [comment]
> What do your dependencies look like in your `brownie-config.yaml`?

depencencies :
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
  compiler:
    solc:
      remappings:
        - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
        - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'

I'm using windows if that made any difference, I guess solidity hates windows?

**Comment by PatrickAlphaC** [comment]
Remove the `@` sign from your imports:

It should be
```
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
```
not
```
import "OpenZeppelin/openzeppelin-contracts@3.4.0/contracts/token/ERC721/ERC721.sol";
```

It looks like you added that in by mistake?

**Comment by PatrickAlphaC** [comment]
Windows should work fine
