### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url:

### ISSUE THREAD

**Issue by caynebrister** [PatrickAlphaC/nft-mix#34]
When running the command 'brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby' it outputs this: 'INFO: Could not find files for the given pattern(s).' a bunch of pointers to the code and the actual error: 'HTTPError: 401 Client Error: Unauthorized for url: https://rinkeby.infura.io/v3/*the ID for my infura project*'. I appreciate anyone that can help, thanks ahead of time.

Also, I should mention I set the necessary PRIVATE_KEY environment variable from my wallet and the needed WEB3_INFURA_PROJECT_ID environment variable from a new and active Infura project.

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue. Does this answer your question? https://ethereum.stackexchange.com/questions/106838/httperror-401-client-error-unauthorized-for-url-https-rinkeby-infura-io-v3

**Comment by caynebrister** [comment]
> Thanks for making this issue. Does this answer your question? https://ethereum.stackexchange.com/questions/106838/httperror-401-client-error-unauthorized-for-url-https-rinkeby-infura-io-v3

Sadly no, I already set the private key and project id in the .env file, and your python program recognizes and uses that environment variable, but for some reason, the link it creates throws error 401 'HTTPError: 401 Client Error: Unauthorized for url: https://rinkeby.infura.io/v3/1xdtqDTiui9BuAIQDoS5J3S9qXh' The last digets here being the infura project id. Also I appreciate the swift response.

**Comment by PatrickAlphaC** [comment]
Hmm... I just tested your `WEB3_INFURA_PROJECT_ID` (FYI, now that it's public, don't use it in the future, cuz anyone could now), and it worked fine for me. I'd bet you have some odd setup or firewall issues... but I'm not sure. 

Could you send what your `.env` file looks like?

**Comment by caynebrister** [comment]
#DO NOT MAKE THIS PUBLIC UNDER ANY CIRCUMSTANCES
export PRIVATE_KEY=*my wallet private key*
export WEB3_INFURA_PROJECT_ID=*the ID for my infura project*
### Optional - don't uncomment if you don't know what they do!
# export ETHERSCAN_TOKEN=asdfasdfasdf
# export IPFS_URL=http://127.0.0.1:5001
# export UPLOAD_IPFS=true
# export PINATA_API_KEY='asdfasdfs'
# export PINATA_API_SECRET='asdfasdfsdf'

This is the code for my .env, the asterisks are where I replaced my actual information.

**Comment by caynebrister** [comment]
I am so sorry to waste your time, I feel like a fool, I took a closer look at the Infura project I had made and it turns out I chose Eth 2 instead of Eth. Sorry again and I appreciate you trying to help me with my dumb mistake😅

**Comment by PatrickAlphaC** [comment]
ahah no worries! Sometimes it takes talking out the problem to figure it out. This is called "rubber ducking". Glad you solved it!

**Comment by PatrickAlphaC** [comment]
(FYI, we can still see your edit history, so please get a new infura key!)

**Comment by caynebrister** [comment]
Okay thank you for the help, I am still a bit of a newbie :) and will do!
