### ISSUE TITLE
Gas Issue

### ISSUE THREAD

**Issue by sluicegoose** [PatrickAlphaC/nft-mix#35]
ValueError: Gas estimation failed: 'invalid opcode: opcode 0xfe not defined'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

How does one set said gas limits?

**Comment by Marcuzzz** [comment]
Hi, 

I'm getting:
```ValueError: insufficient funds for gas * price + value

when running:
``` brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby

I'm using ganache for testing but also tried ...
Tried different things but little bit stuck.

![image](https://user-images.githubusercontent.com/7437046/133059437-d88aa560-9bc0-4da9-9986-f9a35bce4b69.png)

![image](https://user-images.githubusercontent.com/7437046/133059523-69d3aa7a-6fca-4217-9e04-404e5ea2a596.png)

![image](https://user-images.githubusercontent.com/7437046/133059595-35561a39-87dd-46e7-b71f-deb28b1761b4.png)

**Comment by PatrickAlphaC** [comment]
This is likely something else going on. 

What is the tx you're trying to send?

**Comment by sluicegoose** [comment]
Ah! It was a problem with the Rinkbey faucet. I left the comment open because I thought it would be interesting to know. I can close it now.

**Comment by PatrickAlphaC** [comment]
Nice!! Thank you!

Yeah I'm trying to reach out to the rinkeby faucet admin.

**Comment by the-lost-kite** [comment]
> Ah! It was a problem with the Rinkbey faucet. I left the comment open because I thought it would be interesting to know. I can close it now.

How did you closed it?
