### ISSUE TITLE
Gas estimation failed

### ISSUE THREAD

**Issue by priyank2peoplecompany** [PatrickAlphaC/nft-mix#37]
After adding my private key and project id on .env file it's works perfectly yesterday but suddenly i got  the an error  "**Gas estimation failed: 'invalid opcode: opcode 0xfe not defined'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.**" after running deploy file.
(brownie run scripts/advanced_collectible/deploy_advanced.py --network rinkeby)  

![error](https://user-images.githubusercontent.com/79518406/133466795-31b02d55-d554-4c4f-9930-1f03a0fd51ae.jpg)

**Comment by xadhrit** [comment]
try to add some (2-3) more zeros in /scripts/helpful_scripts.py in amount?  Do you get testnet eths and link?

**Comment by priyank2peoplecompany** [comment]
i tried but no luck

**Comment by xadhrit** [comment]
how much ether do you have on rinkeby ?

**Comment by priyank2peoplecompany** [comment]
18.6673 ether i have on rinkeby

**Comment by xadhrit** [comment]
try to re-run scripts in order!
`brownie run scripts/advanced_collectible/deploy_advanced.py --network rinkeby
brownie run scripts/advanced_collectible/fund_collectible.py --network rinkeby
brownie run scripts/advanced_collectible/create_collectible.py --network rinkeby`

check again or can you share more details about you code ?

**Comment by priyank2peoplecompany** [comment]
Still same error.

after taking pull i just updated .env file. It's working 1 day before but now it's not working.

If you want i can upload zip or push code here in new branch

![image](https://user-images.githubusercontent.com/79518406/133564825-ed5fdd61-7f97-4659-bf9e-812d43879096.png)

![image](https://user-images.githubusercontent.com/79518406/133565021-319f1e40-2a54-4e49-ad8f-5e29c01b2b0a.png)

**Comment by xadhrit** [comment]
I cann't see  if you have testnet links. you'll need testnet link in your wallet . Get testnet link :  testnet link[https://faucets.chain.link/] . and in wallet click on add token and after putting you token there you'll get  test link. 10 Link at a time.

**Comment by xadhrit** [comment]
https://faucets.chain.link/

**Comment by priyank2peoplecompany** [comment]
Link added to the meta mask account

![image](https://user-images.githubusercontent.com/79518406/133571701-496c8aa3-68c5-4671-9390-185a15fc8349.png)

![image](https://user-images.githubusercontent.com/79518406/133571805-5670b0d0-4d59-4a9a-b98a-446fb65058d3.png)

**Comment by priyank2peoplecompany** [comment]
Do i need to update private key in .env file ?

**Comment by xadhrit** [comment]
you have to add 0x in your private key

**Comment by priyank2peoplecompany** [comment]
![image](https://user-images.githubusercontent.com/79518406/133574411-dda13d7a-34ff-4216-b693-185155ffae41.png)

This is my .env file and after adding 0x in .env file still got same error

**Comment by xadhrit** [comment]
`source .env`? then try to run scripts

**Comment by priyank2peoplecompany** [comment]
Yes after updating .env  file i run the script

**Comment by PatrickAlphaC** [comment]
> ![image](https://user-images.githubusercontent.com/79518406/133574411-dda13d7a-34ff-4216-b693-185155ffae41.png)
> 
> This is my .env file and after adding 0x in .env file still got same error

Please pull all funds out of this wallet if you have any real money immediately. Create a new metamask and move any real funds you have ASAP

**Comment by PatrickAlphaC** [comment]
What happens if you re-clone the repo?

**Comment by priyank2peoplecompany** [comment]
Thanks for the reply  i didn't try to re-clone let me try and check.

**Comment by priyank2peoplecompany** [comment]
@PatrickAlphaC it's working fine after taking clone do i need to still change the wallet as there isn't ?

**Comment by PatrickAlphaC** [comment]
Glad that worked!

Sorry, what's your new question?

Also, closing for now, feel free to follow up here though.
