### ISSUE TITLE
Issue with infura

### ISSUE THREAD

**Issue by rajuu89** [PatrickAlphaC/nft-mix#4]
when I run this command, I get this error

brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby

 File "brownie/network/web3.py", line 171, in _expand_environment_vars
    raise ValueError(f"Unable to expand environment variable in host setting: '{uri}'")
ValueError: Unable to expand environment variable in host setting: 'https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID

I have setup the WEB3_INFURA_PROJECT_ID and PRIVATE_KEY in .env file but got above issue

**Comment by PatrickAlphaC** [comment]
In your `.env` file, are you using:

```
WEB3_INFURA_PROJECT_ID=asdfasf
```
or
```
$WEB3_INFURA_PROJECT_ID=asdfasf
```
?

**Comment by rajuu89** [comment]
using WEB3_INFURA_PROJECT_ID

**Comment by PatrickAlphaC** [comment]
Yep, I've made an issue on the brownie repo. I jumped the gun here. For the time being, could you run:

```
export WEB3_INFURA_PROJECT_ID=asdfasf
```
in your shell? [You can also learn how to set them here.](https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html)

**Comment by rajuu89** [comment]
I ran this above command now I'm getting below error

ValueError: Gas estimation failed: 'insufficient funds for transfer'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

**Comment by PatrickAlphaC** [comment]
You'll need rinkeby ETH and LINK in your testnet wallet connected to the private key:

https://rinkeby.chain.link/
https://faucet.rinkeby.io/

https://www.youtube.com/watch?v=P7FX_1PePX0

**Comment by PatrickAlphaC** [comment]
For the moment, I'm going to leave this issue open until brownie adds the new env var feature.

**Comment by rajuu89** [comment]
ok thanks let me check

**Comment by rajuu89** [comment]
@PatrickAlphaC when I run on local network, I got this below error

raise ValueError("Explorer API not set for this network")
ValueError: Explorer API not set for this network
Terminating local RPC client...

when I run with rinkeby network, I got this again but I have created ETH and LINK what you say in that video

ValueError: Gas estimation failed: 'insufficient funds for transfer'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

**Comment by PatrickAlphaC** [comment]
You don't have any testnet LINK most likely in your wallet. Do you have Kovan LINK or Rinkeby LINK?

**Comment by rajuu89** [comment]
I have 200 Link in Rinkeby

**Comment by PatrickAlphaC** [comment]
Hmm.... it might still be your WEB3_INFURA_PROJECT_ID then.... What are the chances you could send a video?

**Comment by SheenyMeg** [comment]
> when I run this command, I get this error
> 
> brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby
> 
> File "brownie/network/web3.py", line 171, in _expand_environment_vars
> raise ValueError(f"Unable to expand environment variable in host setting: '{uri}'")
> ValueError: Unable to expand environment variable in host setting: 'https://rinkeby.infura.io/v3/$WEB3_INFURA_PROJECT_ID
> 
> I have setup the WEB3_INFURA_PROJECT_ID and PRIVATE_KEY in .env file but got above issue

You should run **source .env** when everytime open a new terminal or shell

**Comment by PatrickAlphaC** [comment]
You can learn more about them here too: https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html

I'm closing this for now
