### ISSUE TITLE
Contract 'AdvancedCollectible' object has no attribute 'tokenIdToBreed'

### ISSUE THREAD

**Issue by cryptoguy1281** [PatrickAlphaC/nft-mix#40]
I followed all steps from the video. When deploying create_collectible.py I receive the following error

kai@MBP-von-Kai nft-new % brownie run scripts/advanced_collectible/create_collectible.py --network rinkeby
Brownie v1.16.3 - Python development framework for Ethereum

NftNewProject is the active project.

Running 'scripts/advanced_collectible/create_collectible.py::main'...
Transaction sent: 0x94f070239adc0329991d534810760ebe66788cb5147da165cdbe35d24c43d459
  Gas price: 1.000000009 gwei   Gas limit: 178850   Nonce: 48
  AdvancedCollectible.createCollectible confirmed   Block: 9321866   Gas used: 157791 (88.23%)

  AdvancedCollectible.createCollectible confirmed   Block: 9321866   Gas used: 157791 (88.23%)

  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/advanced_collectible/create_collectible.py", line 15, in main
    breed = get_breed(advanced_collectible.tokenIdToBreed(token_id))
  File "brownie/network/contract.py", line 832, in __getattribute__
    raise AttributeError(f"Contract '{self._name}' object has no attribute '{name}'")
AttributeError: Contract 'AdvancedCollectible' object has no attribute 'tokenIdToBreed'
![Bildschirmfoto 2021-09-19 um 22 40 59](https://user-images.githubusercontent.com/87675181/133942372-a9ffbb69-9458-403d-907b-9279965b674a.png)

**Comment by Chokeey** [comment]
same problem, don't know what to do.

**Comment by cryptoguy1281** [comment]
I found the solution ... In the first steps it was 
    mapping(uint256 => Breed) public tokenIdBreed; 
And i really don't know why I missed the sth here...

This needs to be changed to 
    mapping(uint256 => Breed) public tokenId**To**Breed;

Also line 46
        tokenIdToBreed[newItemId] = breed;

After that do the steps again:
brownie run scripts/advanced_collectible/deploy_advanced.py --network rinkeby  
brownie run scripts/advanced_collectible/fund_collectible.py --network rinkeby 
brownie run scripts/advanced_collectible/create_collectible.py --network rinkeby

Else way you'll receive a "Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually." error ;-)

<img width="861" alt="Bildschirmfoto 2021-09-20 um 11 28 54" src="https://user-images.githubusercontent.com/87675181/133981786-6de733cb-f0f7-4df5-b9b1-56d5ebe78198.png">
![Bildschirmfoto 2021-09-20 um 11 32 42](https://user-images.githubusercontent.com/87675181/133981793-89f7c7a6-ae11-4b0a-b30f-889ca76bdc87.png)

**Comment by PatrickAlphaC** [comment]
It looks like the code already resembles this. Are you still seeing issues with the code in this repo?

**Comment by PatrickAlphaC** [comment]
Closing for now
