### ISSUE TITLE
Issue on python script

### ISSUE THREAD

**Issue by EnricoBeltramo** [PatrickAlphaC/nft-mix#46]
I configured as explained in tutorial, I create a wallet on metamask and added 10 LINK in rinkeby but once I run:

brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby

I have follow error:

Running 'scripts/simple_collectible/deploy_simple.py::main'...
rinkeby
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/simple_collectible/deploy_simple.py", line 10, in main
    SimpleCollectible.deploy({"from": dev}, publish_source=publish_source)
  File "brownie/network/contract.py", line 600, in __call__
    return tx["from"].deploy(
  File "brownie/network/account.py", line 508, in deploy
    receipt, exc = self._make_transaction(
  File "brownie/network/account.py", line 743, in _make_transaction
    exc = VirtualMachineError(e)
  File "brownie/exceptions.py", line 85, in __init__
    raise ValueError(exc["message"]) from None
ValueError: insufficient funds for gas * price + value

what should be the issue?

**Comment by camaragon** [comment]
Hey @EnricoBeltramo, I jut ran into this issue. You need some ETH on the rinkeby test network in order to cover the gas prices. I followed this site's instructions [](https://www.geeksforgeeks.org/ethereum-blockchain-getting-free-test-ethers-for-rinkeby-test-network/) to receive some ETH, and it won't cost you anything. I just did this and it worked for me 👍🏼

**Comment by EnricoBeltramo** [comment]
Thank you for support. Effectively with only LINK the transation doesn't work. I added 0.1 ETH in kovan: https://faucets.chain.link/kovan (I tried rinkeby, but still waiting that ETH coming in my wallet..,) and I did successfully the test using kovan:
brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby
