### ISSUE TITLE
Issue with SafeMath?

### ISSUE THREAD

**Issue by mohobson** [PatrickAlphaC/nft-mix#5]
Hi, I am following the tutorial below:

https://www.freecodecamp.org/news/how-to-make-an-nft-and-render-on-opensea-marketplace/

Everything was running smoothly until I ran the following command:

```
brownie run scripts/simple_collectible/deploy_simple.py --network rinkeby
```

Here is the error message from the output:

```
Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/test_contracts/mocks/MockOracle.sol:7:1: ParserError: Source "/Users/me/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.0.2/contracts/src/v0.6/vendor/SafeMath.sol" not found: File not found.
import "@chainlink/contracts/src/v0.6/vendor/SafeMath.sol";
^---------------------------------------------------------^
```

I tried moving forward with the next commands from the tutorial but got the same error. This was no surprise since there was no SafeMath.sol file in that directory as the error points out. 

My next attempt was to download the SafeMath.sol file for v0.6. and manually place it in there. When I tried this, however, I got the following error:

```
Compiling contracts...
  Solc version: 0.4.24
  Optimizer: Enabled  Runs: 200
  EVM Version: Byzantium
CompilerError: solc returned the following errors:

contracts/test_contracts/Oracle.sol:4:1: ParserError: Source "/Users/me/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.0.2/contracts/src/v0.4/vendor/SafeMath.sol" not found: File not found.
import "@chainlink/contracts/src/v0.4/vendor/SafeMath.sol";
^---------------------------------------------------------^
```

Notice that the above error is exactly the same, but now it's trying to use version 0.4 which seems odd to me. It sounds like the SafeMath library has caused some Solidity issues in the past, and that is likely part of the reason for excluding it from v0.8 (https://soliditydeveloper.com/solidity-0.8). Could be unrelated since I'm using v0.6.12, but just wanted to mention it.

Any help would be appreciated, thanks!

**Comment by PatrickAlphaC** [comment]
Thank you so much for making this issue!

We recently updated this to include the latest from the chainlink contracts, and they changed some naming. It should work if you re-pull :D 

Let me know if otherwise.
