### ISSUE TITLE
Cannot use a new/custom contract with the deploy_*.py script.

### ISSUE THREAD

**Issue by magentera** [PatrickAlphaC/nft-mix#50]
![image](https://user-images.githubusercontent.com/17914532/136847470-a8436871-c079-423c-ac3a-712aab011f67.png)

Not sure exactly whats going on. I get the exact same error, even when I follow you exactly. Using the AdvancedCollectible.sol contract.

Is this just a config issue on my end with python? perhaps my version is to new, or too old?

**Comment by PatrickAlphaC** [comment]
What's the name of your contract? It has to be the same name as the contract, not the file. 

Closing for now feel free to follow up .

**Comment by WillChomrak** [comment]
I'm sorry to reopen this, but I am having the same problem. I didn't use custom contract names, I followed the all code in the tutorial exactly (I think) and named the contract AdvancedCollectible. 

Did anyone figure this out? I've been trying to figure this out for two days and am totally stuck. Please help!!!

**Comment by PatrickAlphaC** [comment]
All good! That's what open source is for :)

You probably used `pip install eth-brownie` instead of `pipx`? I highly recommend using `pipx` instead.
