### ISSUE TITLE
The metadata of SHIBA_INU

### ISSUE THREAD

**Issue by SheenyMeg** [PatrickAlphaC/nft-mix#6]
{
    "name": "PUG",
    "description": "An adorable SHIBA_INU pup!",
    "image": "https://ipfs.io/ipfs/QmYx6GsYAKnNzZ9A6NvEKV9nf1VaDzJrqDR23Y8YSkebLU?filename=shiba-inu.png",
    "attributes": [
        {
            "trait_type": "cuteness",
            "value": 100
        }
    ]
}

The name field value here should be SHIBA_INU, right?

**Comment by PatrickAlphaC** [comment]
Thanks for making this, even when you closed it, you're right!
