### ISSUE TITLE
TransactionError: Tx dropped without known replacement: - When I run set_tokenuri.py

### ISSUE THREAD

**Issue by ChristianOConnor** [PatrickAlphaC/nft-mix#61]
I ran `brownie run scripts/rizer_incept/set_tokenuri.py --network rinkeby` and I got this error  
```
TransactionError: Tx dropped without known replacement: 0x0a3c830623e6cd6d07783902f418cd1c3e169ebf1bcb08390f32ddf7aadae291
``` 
  
and when I ran it again I got this  
```
Running 'scripts/rizer_incept/set_tokenuri.py::main'...
Working on rinkeby
The number of tokens you've deployed is: 1
Skipping 0, we already set that tokenURI!
```  
  
The problem is that there is no image for the token on opensea:  
https://testnets.opensea.io/assets/0x85994881438ed80948e2abacf9be29bf3d49f595/0  
<img width="1199" alt="Screen Shot 2021-11-02 at 12 43 45 AM" src="https://user-images.githubusercontent.com/47836708/139788158-18f3864b-a7a9-4be1-9f31-fc30ec81644a.png">
  
  
I correctly uploaded the json metadata and image to ipfs. See these content hashes  
```
QmdxacdJ3VAXThKB2xbYCPBE9KWq8VfGHhdKhrFWMKGVij - metadata json file
QmNfavcLue8H9bsY5CC4v9rx4DSpwrVmEiC5ndjEsM8v1R - png image
```  
  
Do you know what the problem is?

**Comment by PatrickAlphaC** [comment]
Looks like your transactions are going through fine: https://rinkeby.etherscan.io/address/0x85994881438ed80948e2abacf9be29bf3d49f595

This is a known issue, it just means brownie is unsure if the transaction went through correctly.

**Comment by ChristianOConnor** [comment]
Even though the transaction went through it looks like the token uri and/or metadata wasn't set. See  
<img width="1046" alt="Screen Shot 2021-11-02 at 4 11 51 PM" src="https://user-images.githubusercontent.com/47836708/139945161-a359fba0-1c70-4f40-9672-6417bcbf932f.png">
