### ISSUE TITLE
raise ValueError(f"'{value}' is not a valid ETH address") from None

### ISSUE THREAD

**Issue by ChristianOConnor** [PatrickAlphaC/nft-mix#62]
Now I'm getting this error. I think it has something to do with 
```
tx = interface.LinkTokenInterface(link_token).transfer(
        contract_address, amount, {"from": account}
    )
```  
aka line 40 in helpful_scripts.py
  
  
```
File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/rizer_incept/create_incept.py", line 10, in main
    fund_with_link(rizer_incept.address, "as_proxy_for")
  File "./scripts/helpful_scripts.py", line 40, in fund_with_link
    tx = interface.LinkTokenInterface(link_token).transfer(
  File "brownie/network/contract.py", line 615, in __call__
    return Contract.from_abi(self._name, address, self.abi, owner)
  File "brownie/network/contract.py", line 929, in from_abi
    address = _resolve_address(address)
  File "brownie/network/web3.py", line 193, in _resolve_address
    return to_address(domain)
  File "brownie/convert/main.py", line 43, in to_address
    return str(EthAddress(value))
  File "brownie/convert/datatypes.py", line 204, in __new__
    raise ValueError(f"'{value}' is not a valid ETH address") from None
ValueError: 'None' is not a valid ETH address
```  
  
**UPDATE**  
I figured out what the problem was. You have to actually put the chainlink token address into the variable `link_token` so lines 35 to 37 would look like this:  
```
def fund_with_link(
    contract_address, account=None, link_token="0x01BE23585060835E02B77ef475b0Cc51aA1e0709", amount=1000000000000000000
):
```  
  
There's a new problem now, I get this error on line 11 in create_collectible.py  
```
  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/rizer_incept/create_collectible.py", line 11, in main
    transaction = rizer_incept.createCollectible("None", {"from": dev})
  File "brownie/network/contract.py", line 1622, in __call__
    return self.transact(*args)
  File "brownie/network/contract.py", line 1505, in transact
    data=self.encode_input(*args),
  File "brownie/network/contract.py", line 1540, in encode_input
    data = format_input(self.abi, args)
  File "brownie/convert/normalize.py", line 20, in format_input
    raise type(e)(f"{abi['name']} {e}") from None
ValueError: createCollectible Sequence has incorrect length, expected 2 but got 1
```  
  
  
**UPDATE 2**  
  
Okay I solved the above problem by adding `STATIC_SEED = 123` as a variable in create_collectible.py and passing it into the createCollectible function. The contract that I already deployed had an input for STATIC_SEED so I needed to provide one in the script. The problem that I am still having that I cannot seem to solve is the fact that the tokens still appear completely blank in opensea even though I have added the metadata and image uri on chain. I don't understand what the problem is. This is the latest token I minted on Opensea at https://testnets.opensea.io/assets/0x85994881438ed80948e2abacf9be29bf3d49f595/3.  
<img width="1177" alt="Screen Shot 2021-11-02 at 8 24 47 PM" src="https://user-images.githubusercontent.com/47836708/139969396-1530636f-8a1b-42ff-be8f-99fa1d1c7aaa.png">  
  
And here it is on checkmynft.com at https://checkmynft.com/?address=0x85994881438Ed80948E2abacF9BE29Bf3d49f595&id=3  
<img width="1193" alt="Screen Shot 2021-11-02 at 8 25 07 PM" src="https://user-images.githubusercontent.com/47836708/139969453-5c56562e-bbc8-4a1f-b3bf-6ba6ebbf5306.png">  
  
What step am I missing @PatrickAlphaC ?

**Comment by ChristianOConnor** [comment]
I think it has something to do with the fact that account=None. How should I set account to avoid this error?

**Comment by ChristianOConnor** [comment]
I fixed it!! The problem was that I was putting the png file ipfs links in the variable `dog_metadata_dic` instead of the json file links. It was writing the token uri as the raw png and not the json file.  
  
So glad this issue was solved sorry to bother everyone.  
  
P.S. one last question... Everytime a new NFT is minted, the number at the beginning of the new json file increases by 1. This means that the file names will continually change as you mint more tokens. So is there any reason that the `dog_metadata_dic` dictionary values contain a `?filename=0-PUG.json` etc... at the end of them? I just put `https://ipfs.io/ipfs/ + CID hash` as all of my dictionary files and it worked just fine. Is there some security risk or other reason why the `?filename=...` is included at the end of the values?

**Comment by PatrickAlphaC** [comment]
Awesome work!!! Glad you were able to solve it. Sometimes you just need to write out what's wrong :)

And nope! The CID hash works great !! The filename is more for readability. Great question. 

Just a note, we should use `ipfs://CID_HASH` instead of `https://ipfs.io/` moving forward... I should update the package for that. 

And thanks for the kind words :)

**Comment by ChristianOConnor** [comment]
> Awesome work!!! Glad you were able to solve it. Sometimes you just need to write out what's wrong :)
> 
> And nope! The CID hash works great !! The filename is more for readability. Great question.
> 
> Just a note, we should use `ipfs://CID_HASH` instead of `https://ipfs.io/` moving forward... I should update the package for that.
> 
> And thanks for the kind words :)

Awesome thanks! And no prob!
