### ISSUE TITLE
Is there a Metamask and frontend integration in the future?

### ISSUE THREAD

**Issue by ChristianOConnor** [PatrickAlphaC/nft-mix#63]
I love this project, it works great but I have to do it from the command line. I'm trying to make a dapp that mints a certain amount of nfts and has an enum that it picks randomly via chainlink... so essentially my project would be this project exactly but with a frontend that enables metamask and users can mint their own nfts until a certain number of nfts are created. All that would be needed is modifying this project to have a hard cap of nfts mintable and a metamask enabled frontend.  
  
I realize that me wanting to create a project doesn't necessitate you to add new functionality to an already great tutorial, but I feel like that would be a very desired addition for a lot of people. I don't see a lot of tutorials about how to integrate metamask on the browser end. Most tutorials are simply about how to write the contract and how to test it with ganache and truffle. Browser integration is a much needed education topic.  
  
Anyway no pressure just curious if this is on the horizon?

**Comment by PatrickAlphaC** [comment]
It is fren :)

Stay tuned. 

Follow me here on github or on youtube, I've got some stuff in the pipeline. https://www.youtube.com/c/patrickcollins

**Comment by ChristianOConnor** [comment]
Oh amazing! I will! Looking forward to it!
