### ISSUE TITLE
Problem with _setTokenURI()

### ISSUE THREAD

**Issue by elio27** [PatrickAlphaC/nft-mix#64]
Hi!
When I try to compile the code for the SImpleCollectible, I get an error at line 15: Undeclared indentifier for "_setTokenURI()",
can anyone help me please ?
Thanks in advance !

**Comment by PatrickAlphaC** [comment]
Are you using `- OpenZeppelin/openzeppelin-contracts@3.4.0` in your `brownie-config`?
