### ISSUE TITLE
I cant install brownie. This happened.

### ISSUE THREAD

**Issue by Kalusha99** [PatrickAlphaC/nft-mix#65]
![errer1](https://user-images.githubusercontent.com/93787953/141926507-401a4ff3-4526-4cfb-9857-d6416dec0d6a.jpg)
![errer2](https://user-images.githubusercontent.com/93787953/141926517-f053e0fc-bce7-4262-8057-678b424d93b2.jpg)
![errer3](https://user-images.githubusercontent.com/93787953/141926523-404d1926-00d6-4885-8065-81e3a39b3d64.jpg)

Collecting eth-brownie
  Using cached eth_brownie-1.17.1-py3-none-any.whl (221 kB)
Collecting iniconfig==1.1.1
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting hexbytes==0.2.2
  Using cached hexbytes-0.2.2-py3-none-any.whl (6.1 kB)
Collecting py==1.10.0
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting py-solc-ast==1.2.9
  Using cached py_solc_ast-1.2.9-py3-none-any.whl (10 kB)
Collecting websockets==9.1
  Using cached websockets-9.1.tar.gz (76 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm==4.62.3
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting semantic-version==2.8.5
  Using cached semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Collecting hypothesis==6.24.0
  Using cached hypothesis-6.24.0-py3-none-any.whl (381 kB)
Collecting py-solc-x==1.1.1
  Using cached py_solc_x-1.1.1-py3-none-any.whl (15 kB)
Collecting pytest-xdist==1.34.0
  Using cached pytest_xdist-1.34.0-py2.py3-none-any.whl (36 kB)
Collecting regex==2021.10.23
  Using cached regex-2021.10.23-cp310-cp310-win_amd64.whl (273 kB)
Collecting wcwidth==0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting pyrsistent==0.18.0
  Using cached pyrsistent-0.18.0-cp310-cp310-win_amd64.whl
Collecting psutil==5.8.0
  Using cached psutil-5.8.0.tar.gz (470 kB)
  Preparing metadata (setup.py) ... done
Collecting eth-rlp==0.2.1
  Using cached eth_rlp-0.2.1-py3-none-any.whl (5.0 kB)
Collecting pygments-lexer-solidity==0.7.0
  Using cached pygments-lexer-solidity-0.7.0.tar.gz (7.3 kB)
  Preparing metadata (setup.py) ... done
Collecting async-timeout==3.0.1
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting lazy-object-proxy==1.6.0
  Using cached lazy_object_proxy-1.6.0-cp310-cp310-win_amd64.whl
Collecting pycryptodome==3.11.0
  Using cached pycryptodome-3.11.0-cp35-abi3-win_amd64.whl (1.8 MB)
Collecting varint==1.0.2
  Using cached varint-1.0.2.tar.gz (1.9 kB)
  Preparing metadata (setup.py) ... done
Collecting pytest==6.2.5
  Using cached pytest-6.2.5-py3-none-any.whl (280 kB)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting eth-keys==0.3.3
  Using cached eth_keys-0.3.3-py3-none-any.whl (20 kB)
Requirement already satisfied: toolz==0.11.1 in c:\users\kalusha samal\appdata\local\programs\python\python310\lib\site-packages (from eth-brownie) (0.11.1)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting multiaddr==0.0.9
  Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
Collecting yarl==1.7.0
  Using cached yarl-1.7.0-cp310-cp310-win_amd64.whl (122 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting packaging==21.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Collecting pathspec==0.9.0
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting black==21.9b0
  Using cached black-21.9b0-py3-none-any.whl (148 kB)
Collecting execnet==1.9.0
  Using cached execnet-1.9.0-py2.py3-none-any.whl (39 kB)
Collecting pyjwt==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting eth-brownie
  Using cached eth_brownie-1.17.0-py3-none-any.whl (221 kB)
Collecting rlp==1.2.0
  Using cached rlp-1.2.0-py2.py3-none-any.whl (19 kB)
Collecting protobuf==3.18.1
  Using cached protobuf-3.18.1-py2.py3-none-any.whl (174 kB)
Collecting tomli==1.2.1
  Using cached tomli-1.2.1-py3-none-any.whl (11 kB)
Collecting dataclassy==0.11.0
  Using cached dataclassy-0.11.0-py3-none-any.whl (23 kB)
Collecting eth-brownie
  Using cached eth_brownie-1.16.4-py3-none-any.whl (219 kB)
Collecting eth-account==0.5.5
  Using cached eth_account-0.5.5-py3-none-any.whl (100 kB)
Collecting vyper==0.2.16
  Using cached vyper-0.2.16-py3-none-any.whl (236 kB)
Collecting web3==5.23.1
  Using cached web3-5.23.1-py3-none-any.whl (486 kB)
Collecting pygments==2.10.0
  Using cached Pygments-2.10.0-py3-none-any.whl (1.0 MB)
Collecting base58==2.1.0
  Using cached base58-2.1.0-py3-none-any.whl (5.6 kB)
Collecting pytest-forked==1.3.0
  Using cached pytest_forked-1.3.0-py2.py3-none-any.whl (4.7 kB)
Collecting pythx==1.6.1
  Using cached pythx-1.6.1-py2.py3-none-any.whl (39 kB)
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting eth-utils==1.10.0
  Using cached eth_utils-1.10.0-py3-none-any.whl (24 kB)
Collecting eth-event==1.2.3
  Using cached eth_event-1.2.3-py3-none-any.whl (7.3 kB)
Collecting inflection==0.5.0
  Using cached inflection-0.5.0-py2.py3-none-any.whl (5.8 kB)
Collecting lru-dict==1.1.7
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting eth-abi==2.1.1
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Collecting yarl==1.6.3
  Using cached yarl-1.6.3-cp310-cp310-win_amd64.whl
Requirement already satisfied: eth-typing==2.2.2 in c:\users\kalusha samal\appdata\local\programs\python\python310\lib\site-packages (from eth-brownie) (2.2.2)
Collecting mythx-models==1.9.1
  Using cached mythx_models-1.9.1-py2.py3-none-any.whl (82 kB)
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting protobuf==3.18.0
  Using cached protobuf-3.18.0-py2.py3-none-any.whl (174 kB)
Collecting platformdirs==2.3.0
  Using cached platformdirs-2.3.0-py3-none-any.whl (13 kB)
Collecting regex==2021.8.28
  Using cached regex-2021.8.28-cp310-cp310-win_amd64.whl (271 kB)
Collecting urllib3==1.26.6
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting multidict==5.1.0
  Using cached multidict-5.1.0-cp310-cp310-win_amd64.whl
Collecting bitarray==1.2.2
  Using cached bitarray-1.2.2.tar.gz (48 kB)
  Preparing metadata (setup.py) ... done
Collecting dataclassy==0.10.4
  Using cached dataclassy-0.10.4-py3-none-any.whl (23 kB)
Collecting charset-normalizer==2.0.6
  Using cached charset_normalizer-2.0.6-py3-none-any.whl (37 kB)
Collecting python-dotenv==0.16.0
  Using cached python_dotenv-0.16.0-py2.py3-none-any.whl (18 kB)
Collecting pluggy==1.0.0
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting cytoolz==0.11.0
  Using cached cytoolz-0.11.0.tar.gz (477 kB)
  Preparing metadata (setup.py) ... done
Collecting hypothesis==6.21.6
  Using cached hypothesis-6.21.6-py3-none-any.whl (381 kB)
Collecting typing-extensions==3.10.0.2
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Requirement already satisfied: eth-hash[pycryptodome]==0.3.2 in c:\users\kalusha samal\appdata\local\programs\python\python310\lib\site-packages (from eth-brownie) (0.3.2)
Collecting idna==3.2
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting pyyaml==5.4.1
  Using cached PyYAML-5.4.1-cp310-cp310-win_amd64.whl
Collecting prompt-toolkit==3.0.20
  Using cached prompt_toolkit-3.0.20-py3-none-any.whl (370 kB)
Collecting eip712==0.1.0
  Using cached eip712-0.1.0-py3-none-any.whl (13 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting asttokens==2.0.4
  Using cached asttokens-2.0.4-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: pyparsing==2.4.7 in c:\users\kalusha samal\appdata\roaming\python\python310\site-packages (from eth-brownie) (2.4.7)
Collecting ipfshttpclient==0.8.0a2
  Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
Collecting py-solc-x==1.1.0
  Using cached py_solc_x-1.1.0-py3-none-any.whl (15 kB)
Collecting eth-keyfile==0.5.1
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting aiohttp==3.7.4.post0
  Using cached aiohttp-3.7.4.post0-py3-none-any.whl
Collecting sortedcontainers==2.4.0
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting pycryptodome==3.10.1
  Using cached pycryptodome-3.10.1-cp35-abi3-win_amd64.whl (1.6 MB)
Collecting click==8.0.1
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting attrs==21.2.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting netaddr==0.8.0
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting certifi==2021.5.30
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting wrapt==1.12.1
  Using cached wrapt-1.12.1.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting parsimonious==0.8.1
  Using cached parsimonious-0.8.1.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
Collecting jsonschema==3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting vvm==0.1.0
  Using cached vvm-0.1.0-py3-none-any.whl (11 kB)
Requirement already satisfied: colorama in c:\users\kalusha samal\appdata\roaming\python\python310\site-packages (from click==8.0.1->eth-brownie) (0.4.4)
Requirement already satisfied: setuptools in c:\users\kalusha samal\appdata\local\programs\python\python310\lib\site-packages (from jsonschema==3.2.0->eth-brownie) (57.4.0)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting pywin32>=223
  Using cached pywin32-302-cp310-cp310-win_amd64.whl (9.2 MB)
**WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 3.18.0 at https://files.pythonhosted.org/packages/74/4e/9f3cb458266ef5cdeaa1e72a90b9eda100e3d1803cbd7ec02f0846da83c3/protobuf-3.18.0-py2.py3-none-any.whl#sha256=615099e52e9fbc9fde00177267a94ca820ecf4e80093e390753568b7d8cb3c1a (from https://pypi.org/simple/protobuf/))**
Reason for being yanked: This version claims to support Python 2 but does not
Using legacy 'setup.py install' for bitarray, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cytoolz, since package 'wheel' is not installed.
Using legacy 'setup.py install' for lru-dict, since package 'wheel' is not installed.
Using legacy 'setup.py install' for parsimonious, since package 'wheel' is not installed.
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pygments-lexer-solidity, since package 'wheel' is not installed.
Using legacy 'setup.py install' for varint, since package 'wheel' is not installed.
Using legacy 'setup.py install' for websockets, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: cytoolz, six, eth-utils, varint, urllib3, toml, rlp, pyrsistent, pycryptodome, py, pluggy, parsimonious, packaging, netaddr, multidict, iniconfig, idna, hexbytes, eth-keys, charset-normalizer, certifi, base58, attrs, atomicwrites, yarl, typing-extensions, requests, python-dateutil, pytest, multiaddr, jsonschema, inflection, eth-rlp, eth-keyfile, eth-abi, chardet, bitarray, async-timeout, websockets, wcwidth, tomli, sortedcontainers, semantic-version, regex, pywin32, pytest-forked, pyjwt, pygments, protobuf, platformdirs, pathspec, mythx-models, mypy-extensions, lru-dict, ipfshttpclient, execnet, eth-account, dataclassy, click, asttokens, aiohttp, wrapt, web3, vyper, vvm, tqdm, pyyaml, pythx, python-dotenv, pytest-xdist, pygments-lexer-solidity, py-solc-x, py-solc-ast, psutil, prompt-toolkit, lazy-object-proxy, hypothesis, eth-event, eip712, black, eth-brownie   
    Running setup.py install for cytoolz ... error
    **ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kalusha Samal\\AppData\\Local\\Temp\\pip-install-dpntpk_g\\cytoolz_e5881649033440b2b2a1fdc598fa6134\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kalusha Samal\\AppData\\Local\\Temp\\pip-install-dpntpk_g\\cytoolz_e5881649033440b2b2a1fdc598fa6134\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kalusha Samal\AppData\Local\Temp\pip-record-fa_3ffo_\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\Include\cytoolz'
         cwd: C:\Users\Kalusha Samal\AppData\Local\Temp\pip-install-dpntpk_g\cytoolz_e5881649033440b2b2a1fdc598fa6134\
    Complete output (70 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.10\cytoolz
    creating build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.10\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.10\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.10\cytoolz
    creating build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.10\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.10\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    creating build\temp.win-amd64-3.10\Release\cytoolz
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\include -IC:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tccytoolz/dicttoolz.c /Fobuild\temp.win-amd64-3.10\Release\cytoolz/dicttoolz.obj
    dicttoolz.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /EXPORT:PyInit_dicttoolz build\temp.win-amd64-3.10\Release\cytoolz/dicttoolz.obj /OUT:build\lib.win-amd64-3.10\cytoolz\dicttoolz.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\cytoolz\dicttoolz.cp310-win_amd64.lib
       Creating library build\temp.win-amd64-3.10\Release\cytoolz\dicttoolz.cp310-win_amd64.lib and object build\temp.win-amd64-3.10\Release\cytoolz\dicttoolz.cp310-win_amd64.exp   
    Generating code
    Finished generating code
    building 'cytoolz.functoolz' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\include -IC:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tccytoolz/functoolz.c /Fobuild\temp.win-amd64-3.10\Release\cytoolz/functoolz.obj
    functoolz.c
    cytoolz/functoolz.c(23087): warning C4013: '_PyGen_Send' undefined; assuming extern returning int
    cytoolz/functoolz.c(23087): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
    cytoolz/functoolz.c(23092): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
    cytoolz/functoolz.c(23176): warning C4047: '=': 'PyObject *' differs in levels of indirection from 'int'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /EXPORT:PyInit_functoolz build\temp.win-amd64-3.10\Release\cytoolz/functoolz.obj /OUT:build\lib.win-amd64-3.10\cytoolz\functoolz.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\cytoolz\functoolz.cp310-win_amd64.lib
       Creating library build\temp.win-amd64-3.10\Release\cytoolz\functoolz.cp310-win_amd64.lib and object build\temp.win-amd64-3.10\Release\cytoolz\functoolz.cp310-win_amd64.exp   
    functoolz.obj : error LNK2001: unresolved external symbol _PyGen_Send
    build\lib.win-amd64-3.10\cytoolz\functoolz.cp310-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120        
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kalusha Samal\\AppData\\Local\\Temp\\pip-install-dpntpk_g\\cytoolz_e5881649033440b2b2a1fdc598fa6134\\setup.py'"'"'; __file__='"'"'C:\\Users\\Kalusha Samal\\AppData\\Local\\Temp\\pip-install-dpntpk_g\\cytoolz_e5881649033440b2b2a1fdc598fa6134\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Kalusha Samal\AppData\Local\Temp\pip-record-fa_3ffo_\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Kalusha Samal\AppData\Local\Programs\Python\Python310\Include\cytoolz' Check the logs for full command output.**

**Comment by PatrickAlphaC** [comment]
Anything here work? https://ethereum.stackexchange.com/questions/112042/link1120-error-when-attempting-to-install-brownie-with-pipx-install-eth-brownie

Could you please follow up on stackoverflow or stack exchange ETH? This is a question we get a lot. 

Also https://www.youtube.com/watch?v=rcI1_e38BWs

**Comment by Kalusha99** [comment]
it worked man.. thank you so much
