### ISSUE TITLE
I appreciate if you can help me with this warning..

### ISSUE THREAD

**Issue by Kalusha99** [PatrickAlphaC/nft-mix#66]
WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 3.18.0 at https://files.pythonhosted.org/packages/74/4e/9f3cb458266ef5cdeaa1e72a90b9eda100e3d1803cbd7ec02f0846da83c3/protobuf-3.18.0-py2.py3-none-any.whl#sha256=615099e52e9fbc9fde00177267a94ca820ecf4e80093e390753568b7d8cb3c1a (from https://pypi.org/simple/protobuf/))
Reason for being yanked: This version claims to support Python 2 but does not

**Comment by PatrickAlphaC** [comment]
No. I won't download packages to my computer from link I don't understand. Sorry. 

Can you please add in text what your error is? 

Closing for now.
