### ISSUE TITLE
I add environment variables but I cant Activate the env

### ISSUE THREAD

**Issue by Kalusha99** [PatrickAlphaC/nft-mix#67]
source .env
'source' is not recognized as an internal or external command,
operable program or batch file.

**Comment by PatrickAlphaC** [comment]
We've updated the package where you don't have to run `source .env` anymore. So please ignore that step. 

Updated the readme here: https://github.com/PatrickAlphaC/nft-mix/commit/31e3d842a1c05c0df69a4ac7a1f228046d2a0e6d
