### ISSUE TITLE
 Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually

### ISSUE THREAD

**Issue by Daeamon** [PatrickAlphaC/nft-mix#71]
Hello i have an issue with executing deploy_advanced.py script with polygon-test network, but deploy_simple.py work correctly!
What is i doing wrong? 

![Screenshot_16](https://user-images.githubusercontent.com/3263898/145866241-3f154d8f-c769-45f8-93d4-7633f4dbd5bb.png)
![image](https://user-images.githubusercontent.com/3263898/145866390-adb6a9cc-5f87-41bb-a985-f74959b63c3d.png)
![image](https://user-images.githubusercontent.com/3263898/145866425-5a85ab58-eae6-48da-a856-f20c23b4d40d.png)
![image](https://user-images.githubusercontent.com/3263898/145866827-6a1dfc07-b907-491c-93c6-80b507826b9d.png)

**Comment by PatrickAlphaC** [comment]
Mumbai isn't a testnet I bother trying to figure out what's going wrong anymore. Please use an ETH testnet, it's the exact same code.

**Comment by Daeamon** [comment]
> Mumbai isn't a testnet I bother trying to figure out what's going wrong anymore. Please use an ETH testnet, it's the exact same code.

ETH has big fee. I see no reason to use this network. The polygon suits me better. And why did you decide that Mumbai is not a testnet? The first thing that comes out in Google on request is the test network polygon just Mumbai.
![image](https://user-images.githubusercontent.com/3263898/145882663-a3b12fe0-c9ad-4196-b74e-52baddcf6ea3.png)

**Comment by Daeamon** [comment]
And the simple example work correct with mumbai testnet.

**Comment by PatrickAlphaC** [comment]
So you can test on a ETH testnet, but deploy to polygon mainnet. The testnet doesn't really matter since they are both EVM compatible. 

Sorry, Mumbai is a testnet. It's just not a testnet that is fun to debug. 

So you can test on an ETH testnet, but deploy to polygon mainnet. That way your fees stay cheap.

**Comment by Daeamon** [comment]
> So you can test on an ETH testnet, but deploy to polygon mainnet. That way your fees stay cheap.

Ok, thanks I will try this solution.
