### ISSUE TITLE
My NFT

### ISSUE THREAD

**Issue by jayp84847** [PatrickAlphaC/nft-mix#72]
Currently we are working on some NFT projects. And its major problem to upload bulk nft on open sea.

First thank you for your video. I got your video. And we are going to do our work based on your video. These are our requirements will your method can complete it please let me know. 

1. We want to create nft on Ethereum blockchain 
2. We want to make ERC721 smart contract 
3. We want to upload it to opensea mainnet
4. Will there any gas fees?
5. We want to upload NFT with ERC721 smart contract on ETH blockchain on opensea but without minting. User will pay for minting. (Cold mint or Lazy minting)

So will your method can help us in these situations? Please let me know.

**Comment by PatrickAlphaC** [comment]
Hi! Thanks for your questions. This video will show you how to do everything except the lazy minting. You'd have to develop that yourself. You can setup a front end that won't mint the NFT until someone buys it. It'll cost the user some gas fees. 

Thank you!
