### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by eatah** [PatrickAlphaC/nft-mix#79]
![Screenshot 2022-01-23 011914](https://user-images.githubusercontent.com/98250826/150667248-ea2f45a2-c0f8-4a96-88dd-dc43e352c1bf.png)

**Comment by PatrickAlphaC** [comment]
Hi, there isn't enough information for me to go on here, and I'm not sure this is a question for this repo. 

1. `MetaMorphers.sol` has nothing to do with the code in this repo.
2. Please don't use screenshots when referring to code, please use copy-pasted formatted code.  
3. I don't know what you're trying to do.

Please either create a new issue about something on this repo, or it might make sense to take your question elsewhere.
