### ISSUE TITLE
AttributeError: Contract 'AdvancedCollectible' object has no attribute 'tokenCounter'

### ISSUE THREAD

**Issue by Kush1399** [PatrickAlphaC/nft-mix#80]
It's giving this error, don't know what to do? .....
Little help here Mr. Patrick..
<img width="685" alt="Screenshot 2022-01-28 at 9 50 37 AM" src="https://user-images.githubusercontent.com/84185904/151486651-0a189b2a-3616-486d-a50c-99a8c7e9232e.png">
<img width="700" alt="Screenshot 2022-01-28 at 9 50 49 AM" src="https://user-images.githubusercontent.com/84185904/151486660-4c4494bb-e92d-48d9-9ed6-74dbbce36fe0.png">
.

**Comment by PatrickAlphaC** [comment]
When making issues, [please watch this video before moving forward. ](https://www.youtube.com/watch?v=XT8STflvwNo&t=21s) I talk about formatting your code in there. 

Does your `AdvancedCollectible` have a public variable `tokenCounter`? 

Closing for now, feel free to follow up.
