### ISSUE TITLE
Gas estimation failed: 'execution reverted'

### ISSUE THREAD

**Issue by JoshuaRM** [PatrickAlphaC/nft-mix#82]
I see this issue has been brought up previously, however I have not seen many solutions.

I have successfully deployed my contract, as well as funded it with LINK (and verified on etherscan rinkeby).
Both my wallet and the contact have LINK, however the contract has 0 ETH.

Not sure if the ETH balance is the issue, however looking in the repo it does not appear to be funded with ETH.
I have attempted to manually set gas limit as suggested as well.
![image](https://user-images.githubusercontent.com/33873582/155001457-ee5c7eaf-18f2-45b6-9003-815e0bf0df4d.png)

**Comment by PatrickAlphaC** [comment]
Can you add all the steps you took so I can reproduce this issue? Does your wallet have testnet ETH? Did you run all the scripts in order?

**Comment by JoshuaRM** [comment]
Hey Patrick,

I'm following along with your youtube video, and I've done all the required steps so far.
My wallet does have testnet ETH as well as LINK, which has been used to fund the contract.

I've run the deploy, fund, and create, and I face the error at the creation script.
Looking at the contract I can see that it is funded with 2 LINK, but no ETH.

**Comment by PatrickAlphaC** [comment]
Sometimes, one can skip one of the required steps, and 9/10 one is just missed by accident!

Could you please go step by step trying to reproduce the issue and see list the steps you took here?

**Comment by nandorcsupor** [comment]
Hey ! Is this still and issue ? I have something similar going o
![GasIssue](https://user-images.githubusercontent.com/79459355/156421541-e024b10b-d22e-41b3-82a2-e9dc5b0f200f.png)
n

**Comment by PatrickAlphaC** [comment]
These are slighty different errors, but likely have different causes. Could you please make a new issue with all your code and error pasted instead of screenshot? Thanks.

I'm closing this for now, but please feel free to follow up with all your steps to reproduce the error.
