### ISSUE TITLE
Error: Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by SqareMe** [PatrickAlphaC/nft-mix#83]
Please help me get this sorted as I've tried everything, including installing Microsoft Visual C++ and I've tried refreshing VS code but every time I do pip install eth-brownie it comes to nearly the end and gives me this error. What would you recommend that I do?

**Comment by PatrickAlphaC** [comment]
Did you try this: https://stackoverflow.com/questions/70447572/trying-to-pipx-install-brownie-without-installing-ms-visual-c

Or this: https://www.youtube.com/watch?v=rcI1_e38BWs

By downloading this: https://visualstudio.microsoft.com/visual-cpp-build-tools/
