### ISSUE TITLE
 API request failed with: Invalid API Key

### ISSUE THREAD

**Issue by kents00** [PatrickAlphaC/nft-mix#99]
Can anyone explain what is the problem here?? 
I recently edited my keys in the .env file the
`PRIVATE KEY` *Metamask I use this project
`WEB3_INFURA_PROJECT_ID`
`ETHERSCAN_TOKEN`

What API key is needed?? I'm still confused

**Comment by PatrickAlphaC** [comment]
`WEB3_INFURA_PROJECT_ID`: https://infura.io/ project key
`ETHERSCAN_TOKEN`: Etherscan API Key https://info.etherscan.com/api-keys/
